=== witnesslq/com.legend.common/common-core/src/test/resources/Pack8583DicMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.legend.com/Pack8583DicMap.xsd"
	elementFormDefault="qualified">
	<element name="Pack8583DicMap">
		<complexType>
			<sequence>
				<element name="Pack8583Dic" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<!-- 序号 -->
							<element name="BitSeq">						
								<simpleType>
									<restriction base="integer">
										<minInclusive value="0" />
										<maxInclusive value="128" />
									</restriction>
								</simpleType>
							</element>
							<!-- 数据编码 -->
							<element name="DataCode">					
								<simpleType>
									<restriction base="string">
										<pattern value="[0-9][0-9][0-9][0-9]" />
									</restriction>
								</simpleType>
							</element>
							<!-- 数据类型(0:二进制；1:数值；2:字符) -->
							<element name="DataType">					
								<simpleType>
									<restriction base="string">
										<pattern value="[0-9]" />
									</restriction>
								</simpleType>
							</element>
							<!-- 数据长度类型(0:定长；1:1位变长；2:2位变长3；3位变长) -->
							<element name="LenType">					
								<simpleType>
									<restriction base="string">
										<pattern value="[0-9]" />
									</restriction>
								</simpleType>
							</element>
							<!-- 数据长度 -->
							<element name="DataLen">					
								<simpleType>
									<restriction base="integer">
										<minInclusive value="0" />
										<maxInclusive value="999" />
									</restriction>
								</simpleType>
							</element>
							<!-- 小数位数 -->
							<element name="DataDec">					
								<simpleType>
									<restriction base="integer">
										<minInclusive value="0" />
										<maxInclusive value="2" />
									</restriction>
								</simpleType>
							</element>
							<!-- 数据域说明 -->
							<element name="Desc" type="string" />		
							<!-- 是否参与MAB运算 -->
							<element name="MabTag" type="boolean" />	
							<!-- 数据格式化标志 -->
							<element name="Format">		
								<simpleType>
									<restriction base="string">
										<enumeration value="FillZeroLeft" />
									</restriction>
								</simpleType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
			<!-- BIT图长度 -->
			<attribute name="bitMapLen" type="integer" use="required"/>
			<!-- BIT图是否可见 -->
			<attribute name="bitMapVisable" type="boolean" use="required"/>
		</complexType>
	</element>
</schema>

=== witnesslq/com.legend.common/common-core/src/test/resources/Pack8583DicMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<Pack8583DicMap xmlns="http://www.legend.com/Pack8583DicMap.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.legend.com/Pack8583DicMap.xsd Pack8583DicMap.xsd"
	bitMapVisable="false" bitMapLen="128" charsetName="UTF-8">
	<Pack8583Dic>
		<BitSeq mab="true">2</BitSeq>
		<DataCode>0020</DataCode>
		<DataType>A</DataType>
		<LenType>2</LenType>
		<DataLen>19</DataLen>
		<DataDec>0</DataDec>
		<Desc>主帐号</Desc>
		<Format>zero</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">3</BitSeq>
		<DataCode>0030</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>6</DataLen>
		<DataDec>0</DataDec>
		<Desc>交易处理码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">4</BitSeq>
		<DataCode>0040</DataCode>
		<DataType>D</DataType>
		<LenType>0</LenType>
		<DataLen>12</DataLen>
		<DataDec>2</DataDec>
		<Desc>交易金额</Desc>
		<Format>point</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>5</BitSeq>
		<DataCode>0050</DataCode>
		<DataType>D</DataType>
		<LenType>0</LenType>
		<DataLen>12</DataLen>
		<DataDec>2</DataDec>
		<Desc>清算金额</Desc>
		<Format>point</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>6</BitSeq>
		<DataCode>0060</DataCode>
		<DataType>D</DataType>
		<LenType>0</LenType>
		<DataLen>12</DataLen>
		<DataDec>2</DataDec>
		<Desc>持卡人扣账金额</Desc>
		<Format>point</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">7</BitSeq>
		<DataCode>0070</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>10</DataLen>
		<DataDec>0</DataDec>
		<Desc>交易传输时间</Desc>
		<Format>zero</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>9</BitSeq>
		<DataCode>0090</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>8</DataLen>
		<DataDec>0</DataDec>
		<Desc>清算汇率</Desc>
		<Format>zero</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>10</BitSeq>
		<DataCode>0100</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>8</DataLen>
		<DataDec>0</DataDec>
		<Desc>持卡人扣账汇率</Desc>
		<Format>zero</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">11</BitSeq>
		<DataCode>0110</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>6</DataLen>
		<DataDec>0</DataDec>
		<Desc>系统跟踪号</Desc>
		<Format>zero</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>12</BitSeq>
		<DataCode>0120</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>6</DataLen>
		<DataDec>0</DataDec>
		<Desc>受卡方所在地时间</Desc>
		<Format>zero</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>13</BitSeq>
		<DataCode>0130</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>4</DataLen>
		<DataDec>0</DataDec>
		<Desc>受卡方所在地日期</Desc>
		<Format>zero</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>14</BitSeq>
		<DataCode>0140</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>4</DataLen>
		<DataDec>0</DataDec>
		<Desc>卡有效期</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>15</BitSeq>
		<DataCode>0150</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>4</DataLen>
		<DataDec>0</DataDec>
		<Desc>清算日期</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>16</BitSeq>
		<DataCode>0160</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>4</DataLen>
		<DataDec>0</DataDec>
		<Desc>兑换日期</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">18</BitSeq>
		<DataCode>0180</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>4</DataLen>
		<DataDec>0</DataDec>
		<Desc>商户类型</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>19</BitSeq>
		<DataCode>0190</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>3</DataLen>
		<DataDec>0</DataDec>
		<Desc>商户国家代码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>22</BitSeq>
		<DataCode>0220</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>3</DataLen>
		<DataDec>0</DataDec>
		<Desc>服务点输入方式码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>23</BitSeq>
		<DataCode>0230</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>3</DataLen>
		<DataDec>0</DataDec>
		<Desc>卡序列号</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">25</BitSeq>
		<DataCode>0250</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>2</DataLen>
		<DataDec>0</DataDec>
		<Desc>服务点条件码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>26</BitSeq>
		<DataCode>0260</DataCode>
		<DataType>N</DataType>
		<LenType>0</LenType>
		<DataLen>2</DataLen>
		<DataDec>0</DataDec>
		<Desc>服务点PIN获取码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">28</BitSeq>
		<DataCode>0280</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>9</DataLen>
		<DataDec>0</DataDec>
		<Desc>交易费</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">32</BitSeq>
		<DataCode>0320</DataCode>
		<DataType>A</DataType>
		<LenType>2</LenType>
		<DataLen>11</DataLen>
		<DataDec>0</DataDec>
		<Desc>受理机构标识码</Desc>
		<Format>space</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">33</BitSeq>
		<DataCode>0330</DataCode>
		<DataType>A</DataType>
		<LenType>2</LenType>
		<DataLen>11</DataLen>
		<DataDec>0</DataDec>
		<Desc>发送机构标识码</Desc>
		<Format>space</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>35</BitSeq>
		<DataCode>0350</DataCode>
		<DataType>A</DataType>
		<LenType>2</LenType>
		<DataLen>37</DataLen>
		<DataDec>0</DataDec>
		<Desc>第二磁道数据</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>36</BitSeq>
		<DataCode>0360</DataCode>
		<DataType>A</DataType>
		<LenType>3</LenType>
		<DataLen>104</DataLen>
		<DataDec>0</DataDec>
		<Desc>第三磁道数据</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>37</BitSeq>
		<DataCode>0370</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>12</DataLen>
		<DataDec>0</DataDec>
		<Desc>检索参考号</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">38</BitSeq>
		<DataCode>0380</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>6</DataLen>
		<DataDec>0</DataDec>
		<Desc>授权标识应答码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">39</BitSeq>
		<DataCode>0390</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>2</DataLen>
		<DataDec>0</DataDec>
		<Desc>应答码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">41</BitSeq>
		<DataCode>0410</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>8</DataLen>
		<DataDec>0</DataDec>
		<Desc>受卡机终端标识码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq mab="true">42</BitSeq>
		<DataCode>0420</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>15</DataLen>
		<DataDec>0</DataDec>
		<Desc>受卡方标识码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>42</BitSeq>
		<DataCode>0420</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>15</DataLen>
		<DataDec>0</DataDec>
		<Desc>受卡方标识码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>43</BitSeq>
		<DataCode>0430</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>40</DataLen>
		<DataDec>0</DataDec>
		<Desc>受卡方名称地址</Desc>
		<Format>space</Format>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>44</BitSeq>
		<DataCode>0440</DataCode>
		<DataType>A</DataType>
		<LenType>2</LenType>
		<DataLen>25</DataLen>
		<DataDec>0</DataDec>
		<Desc>附加响应数据</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>45</BitSeq>
		<DataCode>0450</DataCode>
		<DataType>A</DataType>
		<LenType>2</LenType>
		<DataLen>79</DataLen>
		<DataDec>0</DataDec>
		<Desc>第一磁道数据</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>48</BitSeq>
		<DataCode>0480</DataCode>
		<DataType>A</DataType>
		<LenType>3</LenType>
		<DataLen>512</DataLen>
		<DataDec>0</DataDec>
		<Desc>附加数据－私有</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>49</BitSeq>
		<DataCode>0490</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>3</DataLen>
		<DataDec>0</DataDec>
		<Desc>交易货币代码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>50</BitSeq>
		<DataCode>0500</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>3</DataLen>
		<DataDec>0</DataDec>
		<Desc>清算货币代码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>51</BitSeq>
		<DataCode>0510</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>3</DataLen>
		<DataDec>0</DataDec>
		<Desc>持卡人账户货币代码</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>52</BitSeq>
		<DataCode>0520</DataCode>
		<DataType>B</DataType>
		<LenType>0</LenType>
		<DataLen>8</DataLen>
		<DataDec>0</DataDec>
		<Desc>个人标识码数据</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>53</BitSeq>
		<DataCode>0530</DataCode>
		<DataType>A</DataType>
		<LenType>0</LenType>
		<DataLen>16</DataLen>
		<DataDec>0</DataDec>
		<Desc>安全控制信息</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>54</BitSeq>
		<DataCode>0540</DataCode>
		<DataType>A</DataType>
		<LenType>3</LenType>
		<DataLen>40</DataLen>
		<DataDec>0</DataDec>
		<Desc>实际余额</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>55</BitSeq>
		<DataCode>0550</DataCode>
		<DataType>A</DataType>
		<LenType>3</LenType>
		<DataLen>255</DataLen>
		<DataDec>0</DataDec>
		<Desc>IC卡数据域</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>57</BitSeq>
		<DataCode>0570</DataCode>
		<DataType>A</DataType>
		<LenType>3</LenType>
		<DataLen>100</DataLen>
		<DataDec>0</DataDec>
		<Desc>附加交易信息</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>58</BitSeq>
		<DataCode>0580</DataCode>
		<DataType>A</DataType>
		<LenType>3</LenType>
		<DataLen>100</DataLen>
		<DataDec>0</DataDec>
		<Desc>IC卡标准的交易数据</Desc>
	</Pack8583Dic>
	<Pack8583Dic>
		<BitSeq>59</BitSeq>
		<DataCode>0590</DataCode>
		<DataType>A</DataType>
		<LenType>3</LenType>
