=== witnesslq/com.legend.common/common-config/etc/cartoon/DataBusConv/DataConvMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.legend.com/DataConvMap.xsd"
	xmlns:p="http://www.legend.com/DataConvMap.xsd"
	elementFormDefault="qualified">

	<element name="DataConvMap">
		<complexType>
			<sequence>
				<element name="DataConv" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="Source" type='string' />
							<element name="Destination" type='string' />
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== witnesslq/com.legend.common/common-config/etc/cartoon/DataBusConv/CPReq_I.databus.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataConvMap xmlns="http://www.legend.com/DataConvMap.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.legend.com/DataConvMap.xsd DataConvMap.xsd">
	<DataConv>
		<Source>cartoon.message.id</Source>
		<Destination>MESSAGEID</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.version</Source>
		<Destination>VERSION</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.instid</Source>
		<Destination>INSTID</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.certid</Source>
		<Destination>CERTID</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.serialno</Source>
		<Destination>SERIALNO</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.date</Source>
		<Destination>DATE</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.signno</Source>
		<Destination>SIGNNO</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.charge</Source>
		<Destination>CHARGE</Destination>
		<Format dec="2">point</Format>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.amount</Source>
		<Destination>AMOUNT</Destination>
		<Format dec="2">point</Format>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.currency</Source>
		<Destination>CURRENCY</Destination>
	</DataConv>
</DataConvMap>

=== witnesslq/com.legend.common/common-config/etc/cartoon/DataBusConv/CPReq_I.conv.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataConvMap xmlns="http://www.legend.com/DataConvMap.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.legend.com/DataConvMap.xsd DataConvMap.xsd">
	<DataConv>
		<Source type="databus">cartoon.message.id</Source>
		<Destination>ID1</Destination>
	</DataConv>
	<DataConv>
		<Source type="databus">cartoon.message.cpreq.id</Source>
		<Destination>ID2</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.date</Source>
		<Destination>REQDATE</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.version</Source>
		<Destination>VERSION</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.currency</Source>
		<Destination>CUR</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.instid</Source>
		<Destination>INSTID</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.certid</Source>
		<Destination>CERTID</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.serialno</Source>
		<Destination>SERIALNO</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.signno</Source>
		<Destination>SIGNNO</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.charge</Source>
		<Destination>CHARGE</Destination>
	</DataConv>
	<DataConv>
		<Source>cartoon.message.cpreq.amount</Source>
		<Destination>AMOUNT</Destination>
	</DataConv>
</DataConvMap>

=== witnesslq/com.legend.common/common-config/etc/cartoon/DataBusConv/CPReq_O.databus.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataConvMap xmlns="http://www.legend.com/DataConvMap.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.legend.com/DataConvMap.xsd DataConvMap.xsd">
	<DataConv>
		<Source>MESSAGEID</Source>
		<Destination>/Cartoon/CpReq/id/dd</Destination>
	</DataConv>
	<DataConv>
		<Source from="constant" type="double">5.89</Source>
		<Destination>/Cartoon/CpReq/id/amount</Destination>
		<Format dec="2">point</Format>
	</DataConv>
	<DataConv>
		<Source from="constant">code</Source>
		<Destination>/Cartoon/CpReq/id/Code</Destination>
	</DataConv>
</DataConvMap>
